### PR TITLE
Fix tensorflow & Pillow versions

### PR DESCRIPTION
**Pull request by duckontheweb**
Relaxes the `tensorflow` and `Pillow` versions to fix an issue with installing these in Python 3.8 and 3.9.

### CODE REVIEW

**Review by guidorice — CHANGES_REQUESTED** [review]
@duckontheweb looks good re: `pillow` version, but when using Python 3.9 I still get an error with the `tensorflow` version:

> ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow==2.4.1

**Comment by duckontheweb** [comment]
> @duckontheweb looks good re: `pillow` version, but when using Python 3.9 I still get an error with the `tensorflow` version:
> 
> > ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
> > ERROR: No matching distribution found for tensorflow==2.4.1

@guidorice I updated the Binder environment and README to to indicate that we only support Python 3.8. I was able to fix the `tensorflow` issue by bumping the requirement to `tensorflow~=2.5`, but there also aren't any 3.9 wheels for the version of `scikit-image` that we require and I wasn't comfortable bumping that version as well. 

I've tested this on Python 3.7 on MacOS as well and it installs correctly, but I didn't want to advertise support for that version until I have some CI in place to test the notebooks as well (I will do that in a separate PR).

**Review by guidorice — APPROVED** [review]
@duckontheweb 👍🏽

**Comment by yayradesouza** [comment]
Binder is working again after this merge. Thanks @duckontheweb and @guidorice .

**Pull request merged**
